import "../reset.css";
import "../globals.css";

import NavBar from "../../components/userProfileLayout/navBar/navBar";
import UserProfileHeader from "../../components/userProfileLayout/userProfileHeader/userProfileHeader";
import UserProfile from "../../components/userProfileLayout/userProfileSidebar/userProfileSidebar";

import styles from "./privateProfile.module.scss";

import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "freenance",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<div className={styles.privateProfileWrap}>
					<div className={styles.privateProfileWrap__navBar}>
						<NavBar />
					</div>
					<div className={styles.privateProfileContent}>
						<div className={styles.privateProfileHeader}>
							<UserProfileHeader />
						</div>
						<div className={styles.privateProfileUserInterface}>
							<UserProfile />
							<div className={styles.privateProfileHeader__adaptive}>
								<UserProfileHeader />
							</div>
							{children}
						</div>
					</div>
				</div>
			</body>
		</html>
	);
}
