import "../reset.css";
import "../globals.css";

import NavBar from "../../components/userProfileLayout/navBar/navBar";
import UserProfileHeader from "../../components/userProfileLayout/userProfileHeader/userProfileHeader";
import UserProfileSidebar from "../../components/userProfileLayout/userProfileSidebar/userProfileSidebar";

import styles from "./privateProfile.module.scss";

import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "freenance",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<div className={styles.privateProfileWrap}>
					<div className={styles.privateProfile__navBar}>
						<NavBar />
					</div>
					<div className={styles.privateProfile__main}>
						{/* <div className={styles.mobileMenu}>
							<UserProfileSidebar />
						</div> */}
						<UserProfileHeader />
						<div className={styles.privateProfileContent}>{children}</div>
					</div>
					<div className={styles.privateProfile__sideBar}>
						<UserProfileSidebar />
					</div>
				</div>
			</body>
		</html>
	);
}
