apiVersion: v1
kind: Service
metadata:
  namespace: {{NAMESPACE}}
  name: finance-frontend-prod
spec:
  selector:
    app: finance-frontend-prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{NAMESPACE}}
  name: finance-frontend-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-frontend-prod
  template:
    metadata:
      labels:
        app: finance-frontend-prod
      annotations:
        fluentd.active: 'true'
    spec:
      containers:
      - name: frontend
        image: freenance/frontend-prod:{{IMAGE_TAG}}
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
