apiVersion: v1
kind: Service
metadata:
  namespace: {{NAMESPACE}}
  name: finance-nginx-dev
spec:
  selector:
    app: finance-nginx-develop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{NAMESPACE}}
  name: finance-nginx-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-nginx-develop
  template:
    metadata:
      labels:
        app: finance-nginx-develop
      annotations:
        fluentd.active: 'true'
    spec:
      containers:
        - name: nginx
          image: freenance/nginx-dev:{{IMAGE_TAG}}
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "50m"
          ports:
            - containerPort: 80