apiVersion: v1
kind: Service
metadata:
  namespace: {{NAMESPACE}}
  name: finance-frontend-dev
spec:
  selector:
    app: finance-frontend-develop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{NAMESPACE}}
  name: finance-frontend-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-frontend-develop
  template:
    metadata:
      labels:
        app: finance-frontend-develop
      annotations:
        fluentd.active: 'true'
    spec:
      containers:
        - name: frontend
          image: freenance/frontend-dev:{{IMAGE_TAG}}
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "50m"
          ports:
            - containerPort: 80
