import "../reset.css";
import "../globals.css";

import MainHeader from "../../components/mainLayout/mainHeader/mainHeader";
import CookiePopupWindowPage from "../../pageElements/homeLayout/cookiePopupWindowPage/cookiePopupWindowPage";
import { rubik } from "../fonts";

import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "freenance",
	description: "Generated by create next app",
};

export default function HomeLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<div className={rubik.className}>
			<MainHeader />
			<CookiePopupWindowPage />
			{children}
		</div>
	);
}
